// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrengthEFcore;

#nullable disable

namespace StrengthEFcore.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20241008163630_rebuild-init")]
    partial class rebuildinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StrengthEFcore.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseBout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ExerciseId")
                        .HasColumnType("int");

                    b.Property<string>("SetRepJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseBout");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseType");
                });

            modelBuilder.Entity("StrengthEFcore.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Olivia Hernandez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Jessica Garcia"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sophia Martinez"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Michael Gonzalez"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Matthew Martin"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Alice Taylor"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Daniel Rodriguez"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Diana Williams"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Olivia Miller"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Matthew Johnson"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Jessica Miller"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Olivia Lopez"
                        },
                        new
                        {
                            Id = 13,
                            Name = "John Johnson"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Emma Moore"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jessica Smith"
                        },
                        new
                        {
                            Id = 16,
                            Name = "Michael Rodriguez"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Michael Taylor"
                        },
                        new
                        {
                            Id = 18,
                            Name = "Sarah Garcia"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Sarah Martinez"
                        },
                        new
                        {
                            Id = 20,
                            Name = "Daniel Martinez"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Sarah Martin"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Jane Jackson"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Sophia Williams"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Alice Wilson"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Fiona Williams"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Ian Garcia"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Chris Johnson"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Alex Thomas"
                        },
                        new
                        {
                            Id = 30,
                            Name = "George Lopez"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Michael Lopez"
                        },
                        new
                        {
                            Id = 32,
                            Name = "David Anderson"
                        },
                        new
                        {
                            Id = 33,
                            Name = "Olivia Wilson"
                        },
                        new
                        {
                            Id = 34,
                            Name = "David Martin"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Jane Davis"
                        },
                        new
                        {
                            Id = 36,
                            Name = "David Jackson"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Jane Martin"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Emma Gonzalez"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Emma Taylor"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Chris Jackson"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Diana Rodriguez"
                        },
                        new
                        {
                            Id = 42,
                            Name = "George Martinez"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Fiona Jones"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Matthew Williams"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Ian Jones"
                        },
                        new
                        {
                            Id = 46,
                            Name = "David Hernandez"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Alice Miller"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Fiona Martinez"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Michael Jackson"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Emma Smith"
                        },
                        new
                        {
                            Id = 51,
                            Name = "David Lopez"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Hannah Johnson"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Olivia Gonzalez"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Jane Jones"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Sarah Davis"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Alice Jones"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Sarah Jones"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Emma Garcia"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Bob Moore"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Hannah Martin"
                        },
                        new
                        {
                            Id = 61,
                            Name = "George Garcia"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Michael Moore"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Alice Rodriguez"
                        },
                        new
                        {
                            Id = 64,
                            Name = "John Hernandez"
                        },
                        new
                        {
                            Id = 65,
                            Name = "Ian Davis"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Jane Rodriguez"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Sophia Martin"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Daniel Hernandez"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Sarah Gonzalez"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Sophia Johnson"
                        },
                        new
                        {
                            Id = 71,
                            Name = "Hannah Brown"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Jessica Davis"
                        },
                        new
                        {
                            Id = 73,
                            Name = "Diana Anderson"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Sophia Rodriguez"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Bob Wilson"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Emma Rodriguez"
                        },
                        new
                        {
                            Id = 77,
                            Name = "John Miller"
                        },
                        new
                        {
                            Id = 78,
                            Name = "John Anderson"
                        },
                        new
                        {
                            Id = 79,
                            Name = "Jane Johnson"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Fiona Martin"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Sophia Gonzalez"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Alex Jackson"
                        },
                        new
                        {
                            Id = 83,
                            Name = "John Rodriguez"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Matthew Rodriguez"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Sarah Rodriguez"
                        },
                        new
                        {
                            Id = 86,
                            Name = "John Gonzalez"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Diana Hernandez"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Ian Martinez"
                        },
                        new
                        {
                            Id = 89,
                            Name = "George Hernandez"
                        });
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("StrengthEFcore.Exercise", b =>
                {
                    b.HasOne("StrengthEFcore.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseBout", b =>
                {
                    b.HasOne("StrengthEFcore.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrengthEFcore.Workout", "Workout")
                        .WithMany("ExerciseBouts")
                        .HasForeignKey("WorkoutId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.HasOne("StrengthEFcore.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrengthEFcore.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.Navigation("ExerciseBouts");
                });
#pragma warning restore 612, 618
        }
    }
}
