// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrengthEFcore;

#nullable disable

namespace StrengthEFcore.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20241008160107_dataseed")]
    partial class dataseed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StrengthEFcore.Exercise", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExerciseTypeId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseBout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ExerciseId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SetRepJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WorkoutId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseBout");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseType", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseType");
                });

            modelBuilder.Entity("StrengthEFcore.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Jane Anderson"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Ian Thomas"
                        },
                        new
                        {
                            Id = "3",
                            Name = "David Johnson"
                        },
                        new
                        {
                            Id = "4",
                            Name = "Fiona Brown"
                        },
                        new
                        {
                            Id = "5",
                            Name = "Jessica Martin"
                        },
                        new
                        {
                            Id = "6",
                            Name = "Jane Williams"
                        },
                        new
                        {
                            Id = "7",
                            Name = "Diana Martin"
                        },
                        new
                        {
                            Id = "8",
                            Name = "Olivia Miller"
                        },
                        new
                        {
                            Id = "9",
                            Name = "Sophia Jackson"
                        },
                        new
                        {
                            Id = "10",
                            Name = "Daniel Anderson"
                        },
                        new
                        {
                            Id = "11",
                            Name = "Ian Johnson"
                        },
                        new
                        {
                            Id = "12",
                            Name = "Sarah Martinez"
                        },
                        new
                        {
                            Id = "13",
                            Name = "Diana Williams"
                        },
                        new
                        {
                            Id = "14",
                            Name = "Emma Martinez"
                        },
                        new
                        {
                            Id = "15",
                            Name = "Matthew Johnson"
                        },
                        new
                        {
                            Id = "16",
                            Name = "Jessica Anderson"
                        },
                        new
                        {
                            Id = "17",
                            Name = "John Johnson"
                        },
                        new
                        {
                            Id = "18",
                            Name = "Alex Gonzalez"
                        },
                        new
                        {
                            Id = "19",
                            Name = "Alex Jones"
                        },
                        new
                        {
                            Id = "20",
                            Name = "Emma Johnson"
                        },
                        new
                        {
                            Id = "21",
                            Name = "David Brown"
                        },
                        new
                        {
                            Id = "22",
                            Name = "Jessica Wilson"
                        },
                        new
                        {
                            Id = "23",
                            Name = "Daniel Johnson"
                        },
                        new
                        {
                            Id = "24",
                            Name = "Chris Martinez"
                        },
                        new
                        {
                            Id = "25",
                            Name = "Michael Wilson"
                        },
                        new
                        {
                            Id = "26",
                            Name = "Jane Taylor"
                        },
                        new
                        {
                            Id = "27",
                            Name = "Emma Miller"
                        },
                        new
                        {
                            Id = "28",
                            Name = "Sophia Thomas"
                        },
                        new
                        {
                            Id = "29",
                            Name = "Sarah Garcia"
                        },
                        new
                        {
                            Id = "30",
                            Name = "Diana Miller"
                        },
                        new
                        {
                            Id = "31",
                            Name = "Alex Martinez"
                        },
                        new
                        {
                            Id = "32",
                            Name = "Bob Lopez"
                        },
                        new
                        {
                            Id = "33",
                            Name = "Matthew Gonzalez"
                        },
                        new
                        {
                            Id = "34",
                            Name = "John Miller"
                        },
                        new
                        {
                            Id = "35",
                            Name = "Sophia Davis"
                        },
                        new
                        {
                            Id = "36",
                            Name = "Matthew Jackson"
                        },
                        new
                        {
                            Id = "37",
                            Name = "Ian Wilson"
                        },
                        new
                        {
                            Id = "38",
                            Name = "Fiona Thomas"
                        },
                        new
                        {
                            Id = "39",
                            Name = "Sophia Gonzalez"
                        },
                        new
                        {
                            Id = "40",
                            Name = "Sarah Gonzalez"
                        },
                        new
                        {
                            Id = "41",
                            Name = "Sarah Miller"
                        },
                        new
                        {
                            Id = "42",
                            Name = "Sarah Rodriguez"
                        },
                        new
                        {
                            Id = "43",
                            Name = "Jessica Miller"
                        },
                        new
                        {
                            Id = "44",
                            Name = "Chris Taylor"
                        },
                        new
                        {
                            Id = "45",
                            Name = "John Moore"
                        },
                        new
                        {
                            Id = "46",
                            Name = "John Jones"
                        },
                        new
                        {
                            Id = "47",
                            Name = "Daniel Lopez"
                        },
                        new
                        {
                            Id = "48",
                            Name = "George Garcia"
                        },
                        new
                        {
                            Id = "49",
                            Name = "Emma Wilson"
                        },
                        new
                        {
                            Id = "50",
                            Name = "Daniel Jones"
                        },
                        new
                        {
                            Id = "51",
                            Name = "Hannah Miller"
                        },
                        new
                        {
                            Id = "52",
                            Name = "Michael Hernandez"
                        },
                        new
                        {
                            Id = "53",
                            Name = "Diana Wilson"
                        },
                        new
                        {
                            Id = "54",
                            Name = "Daniel Hernandez"
                        },
                        new
                        {
                            Id = "55",
                            Name = "Olivia Gonzalez"
                        },
                        new
                        {
                            Id = "56",
                            Name = "John Brown"
                        },
                        new
                        {
                            Id = "57",
                            Name = "Michael Jones"
                        },
                        new
                        {
                            Id = "58",
                            Name = "Jane Jackson"
                        },
                        new
                        {
                            Id = "59",
                            Name = "Diana Brown"
                        },
                        new
                        {
                            Id = "60",
                            Name = "Olivia Jackson"
                        },
                        new
                        {
                            Id = "61",
                            Name = "Sarah Wilson"
                        },
                        new
                        {
                            Id = "62",
                            Name = "Alice Hernandez"
                        },
                        new
                        {
                            Id = "63",
                            Name = "Alice Martin"
                        },
                        new
                        {
                            Id = "64",
                            Name = "Hannah Hernandez"
                        },
                        new
                        {
                            Id = "65",
                            Name = "Hannah Brown"
                        },
                        new
                        {
                            Id = "66",
                            Name = "Michael Anderson"
                        },
                        new
                        {
                            Id = "67",
                            Name = "Olivia Davis"
                        },
                        new
                        {
                            Id = "68",
                            Name = "Matthew Hernandez"
                        },
                        new
                        {
                            Id = "69",
                            Name = "Ian Brown"
                        },
                        new
                        {
                            Id = "70",
                            Name = "Emma Williams"
                        },
                        new
                        {
                            Id = "71",
                            Name = "Alex Martin"
                        },
                        new
                        {
                            Id = "72",
                            Name = "George Jackson"
                        },
                        new
                        {
                            Id = "73",
                            Name = "Jane Smith"
                        },
                        new
                        {
                            Id = "74",
                            Name = "Fiona Martin"
                        },
                        new
                        {
                            Id = "75",
                            Name = "Alex Davis"
                        },
                        new
                        {
                            Id = "76",
                            Name = "Diana Davis"
                        },
                        new
                        {
                            Id = "77",
                            Name = "Diana Jones"
                        },
                        new
                        {
                            Id = "78",
                            Name = "Michael Garcia"
                        },
                        new
                        {
                            Id = "79",
                            Name = "Alex Rodriguez"
                        },
                        new
                        {
                            Id = "80",
                            Name = "John Wilson"
                        },
                        new
                        {
                            Id = "81",
                            Name = "Matthew Moore"
                        },
                        new
                        {
                            Id = "82",
                            Name = "Hannah Wilson"
                        },
                        new
                        {
                            Id = "83",
                            Name = "Olivia Hernandez"
                        },
                        new
                        {
                            Id = "84",
                            Name = "Bob Thomas"
                        },
                        new
                        {
                            Id = "85",
                            Name = "Fiona Gonzalez"
                        },
                        new
                        {
                            Id = "86",
                            Name = "George Taylor"
                        });
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workout");
                });

            modelBuilder.Entity("StrengthEFcore.Exercise", b =>
                {
                    b.HasOne("StrengthEFcore.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseBout", b =>
                {
                    b.HasOne("StrengthEFcore.Exercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("StrengthEFcore.Workout", "Workout")
                        .WithMany("ExerciseBouts")
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Exercise");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.HasOne("StrengthEFcore.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrengthEFcore.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.Navigation("ExerciseBouts");
                });
#pragma warning restore 612, 618
        }
    }
}
