// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StrengthEFcore;

#nullable disable

namespace StrengthEFcore.Migrations
{
    [DbContext(typeof(EntityContext))]
    [Migration("20241009090133_seeding")]
    partial class seeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("StrengthEFcore.Exercise", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ExerciseTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseTypeId");

                    b.ToTable("Exercise");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseBout", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("Id"));

                    b.Property<string>("Exercise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetReps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("WorkoutId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("WorkoutId");

                    b.ToTable("ExerciseBout");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Exercise = "Powerclean",
                            SetReps = "[]",
                            WorkoutId = 1
                        },
                        new
                        {
                            Id = 2,
                            Exercise = "Squat",
                            SetReps = "[]",
                            WorkoutId = 2
                        },
                        new
                        {
                            Id = 3,
                            Exercise = "OverHeadPress",
                            SetReps = "[1]",
                            WorkoutId = 3
                        },
                        new
                        {
                            Id = 4,
                            Exercise = "Squat",
                            SetReps = "[]",
                            WorkoutId = 4
                        },
                        new
                        {
                            Id = 5,
                            Exercise = "OverHeadPress",
                            SetReps = "[1,1,1,1]",
                            WorkoutId = 5
                        },
                        new
                        {
                            Id = 6,
                            Exercise = "Squat",
                            SetReps = "[4,0,1,0]",
                            WorkoutId = 6
                        },
                        new
                        {
                            Id = 7,
                            Exercise = "Deadlift",
                            SetReps = "[0]",
                            WorkoutId = 7
                        },
                        new
                        {
                            Id = 8,
                            Exercise = "Squat",
                            SetReps = "[2,2]",
                            WorkoutId = 8
                        },
                        new
                        {
                            Id = 9,
                            Exercise = "Powerclean",
                            SetReps = "[3,3,4]",
                            WorkoutId = 9
                        },
                        new
                        {
                            Id = 10,
                            Exercise = "Deadlift",
                            SetReps = "[2,4]",
                            WorkoutId = 10
                        },
                        new
                        {
                            Id = 11,
                            Exercise = "Deadlift",
                            SetReps = "[3]",
                            WorkoutId = 11
                        },
                        new
                        {
                            Id = 12,
                            Exercise = "OverHeadPress",
                            SetReps = "[0,3,2]",
                            WorkoutId = 12
                        },
                        new
                        {
                            Id = 13,
                            Exercise = "Squat",
                            SetReps = "[2]",
                            WorkoutId = 13
                        },
                        new
                        {
                            Id = 14,
                            Exercise = "Deadlift",
                            SetReps = "[3,4]",
                            WorkoutId = 14
                        },
                        new
                        {
                            Id = 15,
                            Exercise = "Squat",
                            SetReps = "[3]",
                            WorkoutId = 15
                        },
                        new
                        {
                            Id = 16,
                            Exercise = "Powerclean",
                            SetReps = "[]",
                            WorkoutId = 16
                        },
                        new
                        {
                            Id = 17,
                            Exercise = "Squat",
                            SetReps = "[1,3,0]",
                            WorkoutId = 17
                        },
                        new
                        {
                            Id = 18,
                            Exercise = "OverHeadPress",
                            SetReps = "[0]",
                            WorkoutId = 18
                        },
                        new
                        {
                            Id = 19,
                            Exercise = "OverHeadPress",
                            SetReps = "[0,4,1]",
                            WorkoutId = 19
                        },
                        new
                        {
                            Id = 20,
                            Exercise = "Powerclean",
                            SetReps = "[4]",
                            WorkoutId = 20
                        },
                        new
                        {
                            Id = 21,
                            Exercise = "Squat",
                            SetReps = "[0,4]",
                            WorkoutId = 21
                        },
                        new
                        {
                            Id = 22,
                            Exercise = "Deadlift",
                            SetReps = "[4]",
                            WorkoutId = 22
                        },
                        new
                        {
                            Id = 23,
                            Exercise = "Squat",
                            SetReps = "[3,3,3]",
                            WorkoutId = 23
                        },
                        new
                        {
                            Id = 24,
                            Exercise = "Powerclean",
                            SetReps = "[1,2,0,1]",
                            WorkoutId = 24
                        },
                        new
                        {
                            Id = 25,
                            Exercise = "Deadlift",
                            SetReps = "[3]",
                            WorkoutId = 25
                        },
                        new
                        {
                            Id = 26,
                            Exercise = "BenchPress",
                            SetReps = "[1,3,2,0]",
                            WorkoutId = 26
                        },
                        new
                        {
                            Id = 27,
                            Exercise = "Deadlift",
                            SetReps = "[1,1]",
                            WorkoutId = 27
                        },
                        new
                        {
                            Id = 28,
                            Exercise = "OverHeadPress",
                            SetReps = "[3,3]",
                            WorkoutId = 28
                        },
                        new
                        {
                            Id = 29,
                            Exercise = "Deadlift",
                            SetReps = "[3,4]",
                            WorkoutId = 29
                        },
                        new
                        {
                            Id = 30,
                            Exercise = "Squat",
                            SetReps = "[4,4]",
                            WorkoutId = 30
                        },
                        new
                        {
                            Id = 31,
                            Exercise = "Deadlift",
                            SetReps = "[2,4,0,2]",
                            WorkoutId = 31
                        },
                        new
                        {
                            Id = 32,
                            Exercise = "Powerclean",
                            SetReps = "[2,1]",
                            WorkoutId = 32
                        },
                        new
                        {
                            Id = 33,
                            Exercise = "Squat",
                            SetReps = "[4,4]",
                            WorkoutId = 33
                        },
                        new
                        {
                            Id = 34,
                            Exercise = "Deadlift",
                            SetReps = "[2,4]",
                            WorkoutId = 34
                        },
                        new
                        {
                            Id = 35,
                            Exercise = "BenchPress",
                            SetReps = "[]",
                            WorkoutId = 35
                        },
                        new
                        {
                            Id = 36,
                            Exercise = "BenchPress",
                            SetReps = "[3,3]",
                            WorkoutId = 36
                        },
                        new
                        {
                            Id = 37,
                            Exercise = "Powerclean",
                            SetReps = "[]",
                            WorkoutId = 37
                        },
                        new
                        {
                            Id = 38,
                            Exercise = "BenchPress",
                            SetReps = "[2]",
                            WorkoutId = 38
                        },
                        new
                        {
                            Id = 39,
                            Exercise = "Squat",
                            SetReps = "[]",
                            WorkoutId = 39
                        },
                        new
                        {
                            Id = 40,
                            Exercise = "OverHeadPress",
                            SetReps = "[2]",
                            WorkoutId = 40
                        },
                        new
                        {
                            Id = 41,
                            Exercise = "Powerclean",
                            SetReps = "[0]",
                            WorkoutId = 41
                        },
                        new
                        {
                            Id = 42,
                            Exercise = "BenchPress",
                            SetReps = "[3,4]",
                            WorkoutId = 42
                        },
                        new
                        {
                            Id = 43,
                            Exercise = "OverHeadPress",
                            SetReps = "[1,0,1,2]",
                            WorkoutId = 43
                        },
                        new
                        {
                            Id = 44,
                            Exercise = "OverHeadPress",
                            SetReps = "[1,2]",
                            WorkoutId = 44
                        },
                        new
                        {
                            Id = 45,
                            Exercise = "OverHeadPress",
                            SetReps = "[0,1,4]",
                            WorkoutId = 45
                        },
                        new
                        {
                            Id = 46,
                            Exercise = "BenchPress",
                            SetReps = "[1]",
                            WorkoutId = 46
                        },
                        new
                        {
                            Id = 47,
                            Exercise = "BenchPress",
                            SetReps = "[]",
                            WorkoutId = 47
                        },
                        new
                        {
                            Id = 48,
                            Exercise = "Powerclean",
                            SetReps = "[]",
                            WorkoutId = 48
                        },
                        new
                        {
                            Id = 49,
                            Exercise = "Squat",
                            SetReps = "[1]",
                            WorkoutId = 49
                        },
                        new
                        {
                            Id = 50,
                            Exercise = "BenchPress",
                            SetReps = "[1]",
                            WorkoutId = 50
                        },
                        new
                        {
                            Id = 51,
                            Exercise = "Deadlift",
                            SetReps = "[2]",
                            WorkoutId = 51
                        },
                        new
                        {
                            Id = 52,
                            Exercise = "Deadlift",
                            SetReps = "[3]",
                            WorkoutId = 52
                        },
                        new
                        {
                            Id = 53,
                            Exercise = "Deadlift",
                            SetReps = "[3]",
                            WorkoutId = 53
                        },
                        new
                        {
                            Id = 54,
                            Exercise = "OverHeadPress",
                            SetReps = "[4,0]",
                            WorkoutId = 54
                        },
                        new
                        {
                            Id = 55,
                            Exercise = "OverHeadPress",
                            SetReps = "[]",
                            WorkoutId = 55
                        },
                        new
                        {
                            Id = 56,
                            Exercise = "Powerclean",
                            SetReps = "[4,1,4]",
                            WorkoutId = 56
                        },
                        new
                        {
                            Id = 57,
                            Exercise = "OverHeadPress",
                            SetReps = "[1,4,0]",
                            WorkoutId = 57
                        },
                        new
                        {
                            Id = 58,
                            Exercise = "Deadlift",
                            SetReps = "[4]",
                            WorkoutId = 58
                        },
                        new
                        {
                            Id = 59,
                            Exercise = "BenchPress",
                            SetReps = "[4]",
                            WorkoutId = 59
                        },
                        new
                        {
                            Id = 60,
                            Exercise = "OverHeadPress",
                            SetReps = "[]",
                            WorkoutId = 60
                        },
                        new
                        {
                            Id = 61,
                            Exercise = "Deadlift",
                            SetReps = "[1]",
                            WorkoutId = 61
                        },
                        new
                        {
                            Id = 62,
                            Exercise = "OverHeadPress",
                            SetReps = "[4,4,4]",
                            WorkoutId = 62
                        },
                        new
                        {
                            Id = 63,
                            Exercise = "BenchPress",
                            SetReps = "[3,0,2]",
                            WorkoutId = 63
                        },
                        new
                        {
                            Id = 64,
                            Exercise = "Squat",
                            SetReps = "[2]",
                            WorkoutId = 64
                        },
                        new
                        {
                            Id = 65,
                            Exercise = "Deadlift",
                            SetReps = "[1,2]",
                            WorkoutId = 65
                        },
                        new
                        {
                            Id = 66,
                            Exercise = "Deadlift",
                            SetReps = "[1,4,2,3]",
                            WorkoutId = 66
                        },
                        new
                        {
                            Id = 67,
                            Exercise = "Squat",
                            SetReps = "[2,2,1]",
                            WorkoutId = 67
                        },
                        new
                        {
                            Id = 68,
                            Exercise = "BenchPress",
                            SetReps = "[]",
                            WorkoutId = 68
                        },
                        new
                        {
                            Id = 69,
                            Exercise = "Squat",
                            SetReps = "[3,1,3]",
                            WorkoutId = 69
                        },
                        new
                        {
                            Id = 70,
                            Exercise = "Squat",
                            SetReps = "[4,4]",
                            WorkoutId = 70
                        },
                        new
                        {
                            Id = 71,
                            Exercise = "Powerclean",
                            SetReps = "[4,0,0,4]",
                            WorkoutId = 71
                        },
                        new
                        {
                            Id = 72,
                            Exercise = "BenchPress",
                            SetReps = "[1,2,3]",
                            WorkoutId = 72
                        },
                        new
                        {
                            Id = 73,
                            Exercise = "Powerclean",
                            SetReps = "[4,3]",
                            WorkoutId = 73
                        },
                        new
                        {
                            Id = 74,
                            Exercise = "OverHeadPress",
                            SetReps = "[2,1,3]",
                            WorkoutId = 74
                        },
                        new
                        {
                            Id = 75,
                            Exercise = "Squat",
                            SetReps = "[1,0,0]",
                            WorkoutId = 75
                        },
                        new
                        {
                            Id = 76,
                            Exercise = "BenchPress",
                            SetReps = "[]",
                            WorkoutId = 76
                        },
                        new
                        {
                            Id = 77,
                            Exercise = "OverHeadPress",
                            SetReps = "[4,4,2,3]",
                            WorkoutId = 77
                        },
                        new
                        {
                            Id = 78,
                            Exercise = "BenchPress",
                            SetReps = "[2,0,3]",
                            WorkoutId = 78
                        },
                        new
                        {
                            Id = 79,
                            Exercise = "BenchPress",
                            SetReps = "[3,2]",
                            WorkoutId = 79
                        },
                        new
                        {
                            Id = 80,
                            Exercise = "OverHeadPress",
                            SetReps = "[]",
                            WorkoutId = 80
                        },
                        new
                        {
                            Id = 81,
                            Exercise = "Deadlift",
                            SetReps = "[4]",
                            WorkoutId = 81
                        },
                        new
                        {
                            Id = 82,
                            Exercise = "Squat",
                            SetReps = "[]",
                            WorkoutId = 82
                        },
                        new
                        {
                            Id = 83,
                            Exercise = "Deadlift",
                            SetReps = "[]",
                            WorkoutId = 83
                        },
                        new
                        {
                            Id = 84,
                            Exercise = "Deadlift",
                            SetReps = "[4]",
                            WorkoutId = 84
                        },
                        new
                        {
                            Id = 85,
                            Exercise = "OverHeadPress",
                            SetReps = "[]",
                            WorkoutId = 85
                        },
                        new
                        {
                            Id = 86,
                            Exercise = "BenchPress",
                            SetReps = "[2,4,0]",
                            WorkoutId = 86
                        },
                        new
                        {
                            Id = 87,
                            Exercise = "Powerclean",
                            SetReps = "[0,1]",
                            WorkoutId = 87
                        },
                        new
                        {
                            Id = 88,
                            Exercise = "Squat",
                            SetReps = "[1,4,2,0]",
                            WorkoutId = 88
                        },
                        new
                        {
                            Id = 89,
                            Exercise = "Squat",
                            SetReps = "[0,4,1]",
                            WorkoutId = 89
                        },
                        new
                        {
                            Id = 90,
                            Exercise = "OverHeadPress",
                            SetReps = "[4,1]",
                            WorkoutId = 90
                        });
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ExerciseType");
                });

            modelBuilder.Entity("StrengthEFcore.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ian Lopez"
                        },
                        new
                        {
                            Id = 2,
                            Name = "David Lopez"
                        },
                        new
                        {
                            Id = 3,
                            Name = "John Jones"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Bob Wilson"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Bob Rodriguez"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Diana Johnson"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Jessica Davis"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Olivia Jackson"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Olivia Hernandez"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Alex Jones"
                        },
                        new
                        {
                            Id = 11,
                            Name = "Emma Johnson"
                        },
                        new
                        {
                            Id = 12,
                            Name = "Alice Smith"
                        },
                        new
                        {
                            Id = 13,
                            Name = "Daniel Jackson"
                        },
                        new
                        {
                            Id = 14,
                            Name = "Sarah Davis"
                        },
                        new
                        {
                            Id = 15,
                            Name = "Jessica Garcia"
                        },
                        new
                        {
                            Id = 16,
                            Name = "John Taylor"
                        },
                        new
                        {
                            Id = 17,
                            Name = "Diana Hernandez"
                        },
                        new
                        {
                            Id = 18,
                            Name = "George Garcia"
                        },
                        new
                        {
                            Id = 19,
                            Name = "Chris Smith"
                        },
                        new
                        {
                            Id = 20,
                            Name = "George Martin"
                        },
                        new
                        {
                            Id = 21,
                            Name = "Hannah Jones"
                        },
                        new
                        {
                            Id = 22,
                            Name = "Michael Rodriguez"
                        },
                        new
                        {
                            Id = 23,
                            Name = "Alice Martin"
                        },
                        new
                        {
                            Id = 24,
                            Name = "Hannah Brown"
                        },
                        new
                        {
                            Id = 25,
                            Name = "Michael Jackson"
                        },
                        new
                        {
                            Id = 26,
                            Name = "Emma Thomas"
                        },
                        new
                        {
                            Id = 27,
                            Name = "Sarah Garcia"
                        },
                        new
                        {
                            Id = 28,
                            Name = "Sarah Jones"
                        },
                        new
                        {
                            Id = 29,
                            Name = "Jane Rodriguez"
                        },
                        new
                        {
                            Id = 30,
                            Name = "Chris Miller"
                        },
                        new
                        {
                            Id = 31,
                            Name = "Diana Wilson"
                        },
                        new
                        {
                            Id = 32,
                            Name = "David Taylor"
                        },
                        new
                        {
                            Id = 33,
                            Name = "David Martinez"
                        },
                        new
                        {
                            Id = 34,
                            Name = "Alice Moore"
                        },
                        new
                        {
                            Id = 35,
                            Name = "Jessica Anderson"
                        },
                        new
                        {
                            Id = 36,
                            Name = "David Anderson"
                        },
                        new
                        {
                            Id = 37,
                            Name = "Sarah Wilson"
                        },
                        new
                        {
                            Id = 38,
                            Name = "Sophia Anderson"
                        },
                        new
                        {
                            Id = 39,
                            Name = "Bob Lopez"
                        },
                        new
                        {
                            Id = 40,
                            Name = "Fiona Rodriguez"
                        },
                        new
                        {
                            Id = 41,
                            Name = "Chris Jones"
                        },
                        new
                        {
                            Id = 42,
                            Name = "Sarah Hernandez"
                        },
                        new
                        {
                            Id = 43,
                            Name = "Michael Garcia"
                        },
                        new
                        {
                            Id = 44,
                            Name = "Olivia Moore"
                        },
                        new
                        {
                            Id = 45,
                            Name = "Sophia Williams"
                        },
                        new
                        {
                            Id = 46,
                            Name = "Fiona Jackson"
                        },
                        new
                        {
                            Id = 47,
                            Name = "Olivia Rodriguez"
                        },
                        new
                        {
                            Id = 48,
                            Name = "Hannah Wilson"
                        },
                        new
                        {
                            Id = 49,
                            Name = "Sophia Smith"
                        },
                        new
                        {
                            Id = 50,
                            Name = "Sarah Martin"
                        },
                        new
                        {
                            Id = 51,
                            Name = "Matthew Martinez"
                        },
                        new
                        {
                            Id = 52,
                            Name = "Alice Rodriguez"
                        },
                        new
                        {
                            Id = 53,
                            Name = "Daniel Miller"
                        },
                        new
                        {
                            Id = 54,
                            Name = "Daniel Wilson"
                        },
                        new
                        {
                            Id = 55,
                            Name = "Fiona Anderson"
                        },
                        new
                        {
                            Id = 56,
                            Name = "Michael Jones"
                        },
                        new
                        {
                            Id = 57,
                            Name = "Ian Garcia"
                        },
                        new
                        {
                            Id = 58,
                            Name = "Bob Miller"
                        },
                        new
                        {
                            Id = 59,
                            Name = "Olivia Lopez"
                        },
                        new
                        {
                            Id = 60,
                            Name = "Alice Williams"
                        },
                        new
                        {
                            Id = 61,
                            Name = "Daniel Martinez"
                        },
                        new
                        {
                            Id = 62,
                            Name = "Olivia Johnson"
                        },
                        new
                        {
                            Id = 63,
                            Name = "Hannah Moore"
                        },
                        new
                        {
                            Id = 64,
                            Name = "David Thomas"
                        },
                        new
                        {
                            Id = 65,
                            Name = "George Gonzalez"
                        },
                        new
                        {
                            Id = 66,
                            Name = "Hannah Lopez"
                        },
                        new
                        {
                            Id = 67,
                            Name = "Emma Lopez"
                        },
                        new
                        {
                            Id = 68,
                            Name = "Sophia Hernandez"
                        },
                        new
                        {
                            Id = 69,
                            Name = "Alice Taylor"
                        },
                        new
                        {
                            Id = 70,
                            Name = "Sophia Martin"
                        },
                        new
                        {
                            Id = 71,
                            Name = "David Rodriguez"
                        },
                        new
                        {
                            Id = 72,
                            Name = "Michael Davis"
                        },
                        new
                        {
                            Id = 73,
                            Name = "George Hernandez"
                        },
                        new
                        {
                            Id = 74,
                            Name = "Daniel Gonzalez"
                        },
                        new
                        {
                            Id = 75,
                            Name = "Olivia Miller"
                        },
                        new
                        {
                            Id = 76,
                            Name = "Michael Gonzalez"
                        },
                        new
                        {
                            Id = 77,
                            Name = "Hannah Williams"
                        },
                        new
                        {
                            Id = 78,
                            Name = "Alex Brown"
                        },
                        new
                        {
                            Id = 79,
                            Name = "George Taylor"
                        },
                        new
                        {
                            Id = 80,
                            Name = "Emma Gonzalez"
                        },
                        new
                        {
                            Id = 81,
                            Name = "Sophia Taylor"
                        },
                        new
                        {
                            Id = 82,
                            Name = "Olivia Jones"
                        },
                        new
                        {
                            Id = 83,
                            Name = "Bob Hernandez"
                        },
                        new
                        {
                            Id = 84,
                            Name = "Alex Davis"
                        },
                        new
                        {
                            Id = 85,
                            Name = "Alice Hernandez"
                        },
                        new
                        {
                            Id = 86,
                            Name = "Emma Jackson"
                        },
                        new
                        {
                            Id = 87,
                            Name = "Daniel Hernandez"
                        },
                        new
                        {
                            Id = 88,
                            Name = "Olivia Martin"
                        },
                        new
                        {
                            Id = 89,
                            Name = "John Wilson"
                        },
                        new
                        {
                            Id = 90,
                            Name = "Fiona Hernandez"
                        });
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Workout");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1815),
                            Name = "Ian Lopez's 9 session",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1842),
                            Name = "David Lopez's 9 session",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1847),
                            Name = "John Jones's 9 session",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1851),
                            Name = "Bob Wilson's 9 session",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1855),
                            Name = "Bob Rodriguez's 9 session",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1892),
                            Name = "Diana Johnson's 9 session",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1896),
                            Name = "Jessica Davis's 9 session",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1900),
                            Name = "Olivia Jackson's 9 session",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1903),
                            Name = "Olivia Hernandez's 9 session",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1907),
                            Name = "Alex Jones's 9 session",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1912),
                            Name = "Emma Johnson's 9 session",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1916),
                            Name = "Alice Smith's 9 session",
                            UserId = 12
                        },
                        new
                        {
                            Id = 13,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1919),
                            Name = "Daniel Jackson's 9 session",
                            UserId = 13
                        },
                        new
                        {
                            Id = 14,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1923),
                            Name = "Sarah Davis's 9 session",
                            UserId = 14
                        },
                        new
                        {
                            Id = 15,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1927),
                            Name = "Jessica Garcia's 9 session",
                            UserId = 15
                        },
                        new
                        {
                            Id = 16,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1931),
                            Name = "John Taylor's 9 session",
                            UserId = 16
                        },
                        new
                        {
                            Id = 17,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1935),
                            Name = "Diana Hernandez's 9 session",
                            UserId = 17
                        },
                        new
                        {
                            Id = 18,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1939),
                            Name = "George Garcia's 9 session",
                            UserId = 18
                        },
                        new
                        {
                            Id = 19,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1943),
                            Name = "Chris Smith's 9 session",
                            UserId = 19
                        },
                        new
                        {
                            Id = 20,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1946),
                            Name = "George Martin's 9 session",
                            UserId = 20
                        },
                        new
                        {
                            Id = 21,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1950),
                            Name = "Hannah Jones's 9 session",
                            UserId = 21
                        },
                        new
                        {
                            Id = 22,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1954),
                            Name = "Michael Rodriguez's 9 session",
                            UserId = 22
                        },
                        new
                        {
                            Id = 23,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1957),
                            Name = "Alice Martin's 9 session",
                            UserId = 23
                        },
                        new
                        {
                            Id = 24,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1961),
                            Name = "Hannah Brown's 9 session",
                            UserId = 24
                        },
                        new
                        {
                            Id = 25,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1965),
                            Name = "Michael Jackson's 9 session",
                            UserId = 25
                        },
                        new
                        {
                            Id = 26,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1969),
                            Name = "Emma Thomas's 9 session",
                            UserId = 26
                        },
                        new
                        {
                            Id = 27,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1972),
                            Name = "Sarah Garcia's 9 session",
                            UserId = 27
                        },
                        new
                        {
                            Id = 28,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1976),
                            Name = "Sarah Jones's 9 session",
                            UserId = 28
                        },
                        new
                        {
                            Id = 29,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1979),
                            Name = "Jane Rodriguez's 9 session",
                            UserId = 29
                        },
                        new
                        {
                            Id = 30,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1983),
                            Name = "Chris Miller's 9 session",
                            UserId = 30
                        },
                        new
                        {
                            Id = 31,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1986),
                            Name = "Diana Wilson's 9 session",
                            UserId = 31
                        },
                        new
                        {
                            Id = 32,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1990),
                            Name = "David Taylor's 9 session",
                            UserId = 32
                        },
                        new
                        {
                            Id = 33,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1994),
                            Name = "David Martinez's 9 session",
                            UserId = 33
                        },
                        new
                        {
                            Id = 34,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(1998),
                            Name = "Alice Moore's 9 session",
                            UserId = 34
                        },
                        new
                        {
                            Id = 35,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2002),
                            Name = "Jessica Anderson's 9 session",
                            UserId = 35
                        },
                        new
                        {
                            Id = 36,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2006),
                            Name = "David Anderson's 9 session",
                            UserId = 36
                        },
                        new
                        {
                            Id = 37,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2010),
                            Name = "Sarah Wilson's 9 session",
                            UserId = 37
                        },
                        new
                        {
                            Id = 38,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2013),
                            Name = "Sophia Anderson's 9 session",
                            UserId = 38
                        },
                        new
                        {
                            Id = 39,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2017),
                            Name = "Bob Lopez's 9 session",
                            UserId = 39
                        },
                        new
                        {
                            Id = 40,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2020),
                            Name = "Fiona Rodriguez's 9 session",
                            UserId = 40
                        },
                        new
                        {
                            Id = 41,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2024),
                            Name = "Chris Jones's 9 session",
                            UserId = 41
                        },
                        new
                        {
                            Id = 42,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2028),
                            Name = "Sarah Hernandez's 9 session",
                            UserId = 42
                        },
                        new
                        {
                            Id = 43,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2031),
                            Name = "Michael Garcia's 9 session",
                            UserId = 43
                        },
                        new
                        {
                            Id = 44,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2035),
                            Name = "Olivia Moore's 9 session",
                            UserId = 44
                        },
                        new
                        {
                            Id = 45,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2039),
                            Name = "Sophia Williams's 9 session",
                            UserId = 45
                        },
                        new
                        {
                            Id = 46,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2042),
                            Name = "Fiona Jackson's 9 session",
                            UserId = 46
                        },
                        new
                        {
                            Id = 47,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2046),
                            Name = "Olivia Rodriguez's 9 session",
                            UserId = 47
                        },
                        new
                        {
                            Id = 48,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2050),
                            Name = "Hannah Wilson's 9 session",
                            UserId = 48
                        },
                        new
                        {
                            Id = 49,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2053),
                            Name = "Sophia Smith's 9 session",
                            UserId = 49
                        },
                        new
                        {
                            Id = 50,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2089),
                            Name = "Sarah Martin's 9 session",
                            UserId = 50
                        },
                        new
                        {
                            Id = 51,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2094),
                            Name = "Matthew Martinez's 9 session",
                            UserId = 51
                        },
                        new
                        {
                            Id = 52,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2097),
                            Name = "Alice Rodriguez's 9 session",
                            UserId = 52
                        },
                        new
                        {
                            Id = 53,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2101),
                            Name = "Daniel Miller's 9 session",
                            UserId = 53
                        },
                        new
                        {
                            Id = 54,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2105),
                            Name = "Daniel Wilson's 9 session",
                            UserId = 54
                        },
                        new
                        {
                            Id = 55,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2109),
                            Name = "Fiona Anderson's 9 session",
                            UserId = 55
                        },
                        new
                        {
                            Id = 56,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2112),
                            Name = "Michael Jones's 9 session",
                            UserId = 56
                        },
                        new
                        {
                            Id = 57,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2116),
                            Name = "Ian Garcia's 9 session",
                            UserId = 57
                        },
                        new
                        {
                            Id = 58,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2120),
                            Name = "Bob Miller's 9 session",
                            UserId = 58
                        },
                        new
                        {
                            Id = 59,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2123),
                            Name = "Olivia Lopez's 9 session",
                            UserId = 59
                        },
                        new
                        {
                            Id = 60,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2127),
                            Name = "Alice Williams's 9 session",
                            UserId = 60
                        },
                        new
                        {
                            Id = 61,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2130),
                            Name = "Daniel Martinez's 9 session",
                            UserId = 61
                        },
                        new
                        {
                            Id = 62,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2135),
                            Name = "Olivia Johnson's 9 session",
                            UserId = 62
                        },
                        new
                        {
                            Id = 63,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2138),
                            Name = "Hannah Moore's 9 session",
                            UserId = 63
                        },
                        new
                        {
                            Id = 64,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2142),
                            Name = "David Thomas's 9 session",
                            UserId = 64
                        },
                        new
                        {
                            Id = 65,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2146),
                            Name = "George Gonzalez's 9 session",
                            UserId = 65
                        },
                        new
                        {
                            Id = 66,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2150),
                            Name = "Hannah Lopez's 9 session",
                            UserId = 66
                        },
                        new
                        {
                            Id = 67,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2154),
                            Name = "Emma Lopez's 9 session",
                            UserId = 67
                        },
                        new
                        {
                            Id = 68,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2157),
                            Name = "Sophia Hernandez's 9 session",
                            UserId = 68
                        },
                        new
                        {
                            Id = 69,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2161),
                            Name = "Alice Taylor's 9 session",
                            UserId = 69
                        },
                        new
                        {
                            Id = 70,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2165),
                            Name = "Sophia Martin's 9 session",
                            UserId = 70
                        },
                        new
                        {
                            Id = 71,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2169),
                            Name = "David Rodriguez's 9 session",
                            UserId = 71
                        },
                        new
                        {
                            Id = 72,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2172),
                            Name = "Michael Davis's 9 session",
                            UserId = 72
                        },
                        new
                        {
                            Id = 73,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2176),
                            Name = "George Hernandez's 9 session",
                            UserId = 73
                        },
                        new
                        {
                            Id = 74,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2180),
                            Name = "Daniel Gonzalez's 9 session",
                            UserId = 74
                        },
                        new
                        {
                            Id = 75,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2183),
                            Name = "Olivia Miller's 9 session",
                            UserId = 75
                        },
                        new
                        {
                            Id = 76,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2186),
                            Name = "Michael Gonzalez's 9 session",
                            UserId = 76
                        },
                        new
                        {
                            Id = 77,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2190),
                            Name = "Hannah Williams's 9 session",
                            UserId = 77
                        },
                        new
                        {
                            Id = 78,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2193),
                            Name = "Alex Brown's 9 session",
                            UserId = 78
                        },
                        new
                        {
                            Id = 79,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2197),
                            Name = "George Taylor's 9 session",
                            UserId = 79
                        },
                        new
                        {
                            Id = 80,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2201),
                            Name = "Emma Gonzalez's 9 session",
                            UserId = 80
                        },
                        new
                        {
                            Id = 81,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2205),
                            Name = "Sophia Taylor's 9 session",
                            UserId = 81
                        },
                        new
                        {
                            Id = 82,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2208),
                            Name = "Olivia Jones's 9 session",
                            UserId = 82
                        },
                        new
                        {
                            Id = 83,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2211),
                            Name = "Bob Hernandez's 9 session",
                            UserId = 83
                        },
                        new
                        {
                            Id = 84,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2215),
                            Name = "Alex Davis's 9 session",
                            UserId = 84
                        },
                        new
                        {
                            Id = 85,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2219),
                            Name = "Alice Hernandez's 9 session",
                            UserId = 85
                        },
                        new
                        {
                            Id = 86,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2222),
                            Name = "Emma Jackson's 9 session",
                            UserId = 86
                        },
                        new
                        {
                            Id = 87,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2226),
                            Name = "Daniel Hernandez's 9 session",
                            UserId = 87
                        },
                        new
                        {
                            Id = 88,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2229),
                            Name = "Olivia Martin's 9 session",
                            UserId = 88
                        },
                        new
                        {
                            Id = 89,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2233),
                            Name = "John Wilson's 9 session",
                            UserId = 89
                        },
                        new
                        {
                            Id = 90,
                            DateTime = new DateTime(2024, 10, 9, 5, 1, 33, 18, DateTimeKind.Local).AddTicks(2237),
                            Name = "Fiona Hernandez's 9 session",
                            UserId = 90
                        });
                });

            modelBuilder.Entity("StrengthEFcore.Exercise", b =>
                {
                    b.HasOne("StrengthEFcore.ExerciseType", "ExerciseType")
                        .WithMany()
                        .HasForeignKey("ExerciseTypeId");

                    b.Navigation("ExerciseType");
                });

            modelBuilder.Entity("StrengthEFcore.ExerciseBout", b =>
                {
                    b.HasOne("StrengthEFcore.Workout", "Workout")
                        .WithMany("ExerciseBouts")
                        .HasForeignKey("WorkoutId");

                    b.Navigation("Workout");
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.HasOne("StrengthEFcore.User", "User")
                        .WithMany("Workouts")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("StrengthEFcore.User", b =>
                {
                    b.Navigation("Workouts");
                });

            modelBuilder.Entity("StrengthEFcore.Workout", b =>
                {
                    b.Navigation("ExerciseBouts");
                });
#pragma warning restore 612, 618
        }
    }
}
